version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - '8080:80'
    depends_on:
      - app
      - db
    networks:
      - app-node-network

  app:
    build:
      context: ./node
    container_name: app
    volumes:
      - ./node:/usr/src/app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && npm run start"
    tty: true
    depends_on:
      - db
    networks:
      - app-node-network

  db:
    build:
      context: ./sql
      dockerfile: Dockerfile
    command: --innodb-use-native-aio=0
    container_name: sql
    restart: always
    tty: true
    volumes:
      - ./sql:/docker-entrypoint-init.d
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - app-node-network

networks:
  app-node-network:
    driver: bridge
